# Generated by Django 4.2.1 on 2023-05-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='compromisso',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
